server:
  port: 8080




beedata: bee-config.yaml,setup.sh,setupServer.sh,transferPrivateKey.sh,uninstall.sh,clearBeeLog.sh,version.txt,beeRestart.sh,restart.sh

bee:
  clef:
    version: https://github.com/ethersphere/bee-clef/releases/download/v0.4.12/bee-clef_0.4.12_amd64.rpm
    rpm: bee-clef_0.4.12_amd64.rpm
  version: https://github.com/ethersphere/bee/releases/download/v0.6.1/bee_0.6.1_386.rpm
  rpm: bee_0.6.1_386.rpm
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8
    suffix: .html
    mode: HTML
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bee?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.floatcloud.beefz.entity
